import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { IDLE_STATUS, LOADING_STATUS, ERROR_STATUS } from "../../constants/general";
import { fetchCountries } from "./countriesAPI";

const initialState = {
    countries: [],
    status: IDLE_STATUS
};

export const fetchAllCountries = createAsyncThunk(
    'countries/fetchCountries',
    async () => {
      return await fetchCountries();
    }
  );

export const countriesSlice = createSlice({
    name: 'countries',
    initialState,
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
      builder
        .addCase(fetchAllCountries.pending, (state) => {
            state.status = LOADING_STATUS;
        })
        .addCase(fetchAllCountries.fulfilled, (state, action) => {
            state.status = IDLE_STATUS;
            state.countries = action.payload;
        })
        .addCase(fetchAllCountries.rejected, (state) => {
            state.status = ERROR_STATUS
        });
    },
  });

export default countriesSlice.reducer;